version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy-be
    overwrite: yes

permissions:
  - object: /home/ubuntu/deploy-be
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
